title: Joel's Page
author: Joel Gorder
email: gorder.joel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My first webpage using GitHub Pages

# social links
twitter_username: your-twitter-handle
github_username:  jogo9225

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
